package com.uhg.claimsdemoproject;

import com.uhg.claimsdemoproject.Claim;
import com.uhg.claimsdemoproject.ClaimLine;
import com.uhg.claimsdemoproject.ParentCode;

rule "Row 1 ParentCodeTimePeriodRules"
    dialect "mvel"
	when
		$claim : Claim( $claimLines: claimLineList )
		$claimLine : ClaimLine(program_type == "OTP") from $claimLines
	then
        ParentCode code = new ParentCode();
		code.setCodeValue("H0020");
		code.setCodeType("PARENT_CODE");
		$claimLine.addParentCode(code);
		$claimLine.setTime_period("W");
end

