package com.uhg.claimsdemoproject;

import com.uhg.claimsdemoproject.Claim;
import com.uhg.claimsdemoproject.ClaimLine;
import com.uhg.claimsdemoproject.ParentCode;

rule "Row 1 ParentCodeTimePeriodRules"
	when
		$claim : Claim( $claimLines: claimLineList )
		$claimLine : ClaimLine(program_type == "OTP") from $claimLines
	then
        ParentCode code = new ParentCode();
		
		$claimLine.setTime_Period("W");
end

