package com.uhg.claimsdemoproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ClaimLine implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Billing Code")
	private java.lang.String billing_code;
	@org.kie.api.definition.type.Label("Program Type")
	private java.lang.String program_type;
	@org.kie.api.definition.type.Label("Time Period")
	private java.lang.String time_period;
	@org.kie.api.definition.type.Label("Claim Line Identifier")
	private int claimLineId;
	@org.kie.api.definition.type.Label("Attribute1")
	private java.lang.String attr1;
	@org.kie.api.definition.type.Label("Attribute2")
	private java.lang.String attr2;

	@org.kie.api.definition.type.Label("Parent Code List")
	private java.util.List<com.uhg.claimsdemoproject.ParentCode> parent_code_list;

	public ClaimLine() {
	}

	public java.lang.String getBilling_code() {
		return this.billing_code;
	}

	public void setBilling_code(java.lang.String billing_code) {
		this.billing_code = billing_code;
	}

	public java.lang.String getProgram_type() {
		return this.program_type;
	}

	public void setProgram_type(java.lang.String program_type) {
		this.program_type = program_type;
	}

	public java.lang.String getTime_period() {
		return this.time_period;
	}

	public void setTime_period(java.lang.String time_period) {
		this.time_period = time_period;
	}

	public int getClaimLineId() {
		return this.claimLineId;
	}

	public void setClaimLineId(int claimLineId) {
		this.claimLineId = claimLineId;
	}

	public java.lang.String getAttr1() {
		return this.attr1;
	}

	public void setAttr1(java.lang.String attr1) {
		this.attr1 = attr1;
	}

	public java.lang.String getAttr2() {
		return this.attr2;
	}

	public void setAttr2(java.lang.String attr2) {
		this.attr2 = attr2;
	}

	/* This is the custom code added to produce a list */
	/* to solve the issue #1 */

	public void addParentCode(com.uhg.claimsdemoproject.ParentCode code) {
		if (this.parent_code_list == null) {
			this.parent_code_list = new java.util.ArrayList<com.uhg.claimsdemoproject.ParentCode>();
			this.parent_code_list.add(code);
		} else {
			this.parent_code_list.add(code);
		}

	}

	public java.util.List<com.uhg.claimsdemoproject.ParentCode> getParent_code_list() {
		return this.parent_code_list;
	}

	public void setParent_code_list(
			java.util.List<com.uhg.claimsdemoproject.ParentCode> parent_code_list) {
		this.parent_code_list = parent_code_list;
	}

	public ClaimLine(
			java.lang.String billing_code,
			java.lang.String program_type,
			java.lang.String time_period,
			int claimLineId,
			java.lang.String attr1,
			java.lang.String attr2,
			java.util.List<com.uhg.claimsdemoproject.ParentCode> parent_code_list) {
		this.billing_code = billing_code;
		this.program_type = program_type;
		this.time_period = time_period;
		this.claimLineId = claimLineId;
		this.attr1 = attr1;
		this.attr2 = attr2;
		this.parent_code_list = parent_code_list;
	}

}