package com.uhg.claimsdemoproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ParentCode implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public ParentCode() {
    }




}