package com.uhg.claimsdemoproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ParentCode implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Code Value")
	private java.lang.String codeValue;

	private java.lang.String codeType;

	@org.kie.api.definition.type.Label(value = "Time Period")
	private java.lang.String timePeriod;

	public ParentCode() {
	}

	public java.lang.String getCodeValue() {
		return this.codeValue;
	}

	public void setCodeValue(java.lang.String codeValue) {
		this.codeValue = codeValue;
	}

	public java.lang.String getCodeType() {
		return this.codeType;
	}

	public void setCodeType(java.lang.String codeType) {
		this.codeType = codeType;
	}

	public java.lang.String getTimePeriod() {
		return this.timePeriod;
	}

	public void setTimePeriod(java.lang.String timePeriod) {
		this.timePeriod = timePeriod;
	}

	public ParentCode(java.lang.String codeValue, java.lang.String codeType,
			java.lang.String timePeriod) {
		this.codeValue = codeValue;
		this.codeType = codeType;
		this.timePeriod = timePeriod;
	}

}